{
 "title": "0 Rates & Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB size, Mb",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"usersdb\"} / 1024 / 1024",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "commits + rollbacks",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"usersdb\"}[1m]) + rate(pg_stat_database_xact_rollback{datname=\"usersdb\"}[1m])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "I/O Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"usersdb\"}[1m])",
     "legendFormat": "disk reads"
    },
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"usersdb\"}[1m])",
     "legendFormat": "cache hits"
    }
   ]
  },
  { "title": "Kube", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU usage at $namespace, %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m]) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by $namespace, Mb",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (container_memory_working_set_bytes{namespace=\"$namespace\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage total, %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\r\n  rate(container_cpu_usage_seconds_total[1m]) * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage total, Mb",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Error rate by host",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (host) (rate(nginx_ingress_controller_requests{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum by (host) (rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.5, 0.95, 0.99, max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le, host))",
     "legendFormat": "p95 {{host}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le, host))",
     "legendFormat": "p99 {{host}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) by (le, host))",
     "legendFormat": "p50 {{host}}"
    },
    {
     "expr": "max(rate(nginx_ingress_controller_request_duration_seconds_bucket{le=\"+Inf\"}[1m]))",
     "legendFormat": "max {{host}}"
    }
   ]
  },
  { "title": "User service API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Error Rate (5xx) by API Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate( http_server_requests_seconds_count{status=~\"5..\"}[1m] ))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by API Method (p50, p95, p99, max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{uri !~ \"^/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "p50 - {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri !~ \"^/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "p95 - {{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri !~ \"^/actuator/.*\"}[1m])) by (le, method, uri))",
     "legendFormat": "p99 - {{method}} {{uri}}"
    },
    {
     "expr": "max(http_server_requests_seconds_max{uri !~ \"^/actuator/.*\"}) by (method, uri)",
     "legendFormat": "max - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "RPS by API Method",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri !~ \"^/actuator/.*\"}[1m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}